Vic3ToHoI4Tests.vcxproj, Vic3ToHoi4.sln, Vic3ToHoi4.vcxproj
=> Remove debug build

.github/workflows/find_braces_mismatches.yml
=> Add a check for mismatched braces in data files

.gitmodules
=> Update .gitmodules to allow cloning via HTTPS

.github/workflows/linux_coverage.yml, CMakeLists.txt, README.md
=> Set up code coverage reports

.github/workflows/windows_build_test_and_push.yml
=> Upload artifacts from pull requests

.github/workflows/windows_build_test_and_push.yml
Should prevent some user issues.
=> Use local action to build self-contained frontend + updater

data/fronter/fronter-configuration.txt
=> Fix fronter config.

src/mappers/provinces/province_mapper_importer.cpp, src/mappers/provinces/province_mapping_importer.cpp, src/vic3_world/countries/vic3_countries_importer.cpp, src/vic3_world/countries/vic3_country_importer.cpp, src/vic3_world/states/vic3_state_importer.cpp, src/vic3_world/states/vic3_states_importer.cpp, src/vic3_world/world/vic3_world_importer.cpp
=> Use IgnoreUnregisteredItems()

data/configurables/province_mappings.txt
* Styria
* East Slovakia
* East Galicia
* Central Hungary
* Bekes
* Transdanubia
* Delvidek
* Banat
* West Slovakia
* Southern Transylvania
* Northern Transylvania
* Moldavia
* Wallachia
=> Update province mappings Central Europe

src/hoi4_world/states/hoi4_states_converter.cpp
=> Skip non-land provinces when converting states

data/configurables/province_mappings.txt
* Mazovia
* Silesia
* Greater Poland
* Lesser Poland
* West Prussia
* East Prussia
* Posen
* West Galicia
=> Poland province mappings

src/maps/map_data_tests.cpp
Saves about one second on windows, but 38 seconds on linux.
=> Speed up slow tests

Vic3ToHoi4.vcxproj.user, src/hoi4_world/countries/hoi4_countries_converter.cpp, src/hoi4_world/countries/hoi4_countries_converter.h, src/hoi4_world/countries/hoi4_countries_converter_tests.cpp, src/hoi4_world/countries/hoi4_country.h, src/hoi4_world/countries/hoi4_country_converter.cpp, src/hoi4_world/countries/hoi4_country_converter.h, src/hoi4_world/countries/hoi4_country_converter_tests.cpp, src/hoi4_world/states/hoi4_states.h, src/hoi4_world/states/hoi4_states_converter.cpp, src/hoi4_world/states/hoi4_states_converter_tests.cpp, src/hoi4_world/world/hoi4_world_converter.cpp, src/out_hoi4/countries/out_countries_tests.cpp, src/out_hoi4/countries/out_country.cpp, src/vic3_world/countries/vic3_country.h, src/vic3_world/countries/vic3_country_importer.cpp, src/vic3_world/countries/vic3_country_importer.h, src/vic3_world/countries/vic3_country_importer_tests.cpp
=> Convert capital states

src/out_hoi4/countries/out_countries_tests.cpp, src/out_hoi4/countries/out_country.cpp, src/out_hoi4/countries/out_country_tests.cpp
=> Static versions of some country defaults.

src/hoi4_world/map/buildings_creator_tests.cpp, src/hoi4_world/map/strategic_regions_tests.cpp, src/hoi4_world/states/hoi4_state.h, src/hoi4_world/states/hoi4_states_converter.cpp, src/hoi4_world/states/hoi4_states_converter_tests.cpp, src/hoi4_world/world/hoi4_world_converter_tests.cpp, src/out_hoi4/map/out_rocket_sites_tests.cpp, src/out_hoi4/states/out_state.cpp, src/out_hoi4/states/out_state_tests.cpp, src/out_hoi4/states/out_states_tests.cpp, src/out_hoi4/world/out_world_tests.cpp, src/vic3_world/states/vic3_state.h, src/vic3_world/states/vic3_state_importer.cpp, src/vic3_world/states/vic3_state_importer.h, src/vic3_world/states/vic3_state_importer_tests.cpp, src/vic3_world/states/vic3_states_importer_tests.cpp
Fixes #59 
Also some updates to State initialization making things noisy. Sorry about that.
=> Convert population to manpower

src/hoi4_world/states/hoi4_state.h, src/hoi4_world/states/hoi4_states_converter.cpp, src/hoi4_world/states/hoi4_states_converter_tests.cpp, src/out_hoi4/states/out_state.cpp, src/out_hoi4/states/out_state_tests.cpp, src/vic3_world/states/vic3_state.h, src/vic3_world/states/vic3_state_importer.cpp, src/vic3_world/states/vic3_state_importer.h, src/vic3_world/states/vic3_state_importer_tests.cpp
=> Convert Industry

src/hoi4_world/localizations/localizations.h, src/hoi4_world/localizations/localizations_converter.cpp, src/hoi4_world/localizations/localizations_converter.h, src/hoi4_world/localizations/localizations_converter_tests.cpp, src/hoi4_world/world/hoi4_world_converter.cpp, src/hoi4_world/world/hoi4_world_converter_tests.cpp, src/out_hoi4/localizations/out_localizations.cpp, src/out_hoi4/localizations/out_localizations_tests.cpp, src/out_hoi4/world/out_world_tests.cpp, src/vic3_world/states/state_region.h
=> Victory point localizations

src/hoi4_world/states/hoi4_states_converter.cpp, src/hoi4_world/states/hoi4_states_converter.h, src/hoi4_world/states/hoi4_states_converter_tests.cpp, src/hoi4_world/world/hoi4_world_converter.cpp
=> Convert dockyards

data/configurables/division_templates.txt, data/test_files/configurables/division_templates.txt, src/out_hoi4/countries/out_countries.cpp, src/out_hoi4/countries/out_countries_tests.cpp, src/out_hoi4/countries/out_country.cpp, src/out_hoi4/countries/out_country_tests.cpp, src/out_hoi4/out_mod.cpp, src/out_hoi4/world/out_world_tests.cpp
=> Hand out basic division templates

data/configurables/province_mappings.txt
Swiss Alp correction, contiguous Modena, contiguous Algiers
=> North Italy adjustment

src/hoi4_world/countries/hoi4_countries_converter.cpp, src/hoi4_world/countries/hoi4_countries_converter.h, src/hoi4_world/countries/hoi4_countries_converter_tests.cpp, src/hoi4_world/countries/hoi4_country_converter.cpp, src/hoi4_world/countries/hoi4_country_converter.h, src/hoi4_world/countries/hoi4_country_converter_tests.cpp, src/hoi4_world/world/hoi4_world_converter.cpp
=> Convert Backup Capitals

data/blank_mod/common/ideologies/00_ideologies.txt
=> Lower required world tension

src/out_hoi4/states/out_state.cpp, src/out_hoi4/states/out_state_tests.cpp
pull request for 1 line of code... you're welcome
=> add infrastructure as default value

src/hoi4_world/countries/hoi4_countries_converter_tests.cpp, src/hoi4_world/countries/hoi4_country_converter.cpp, src/hoi4_world/countries/hoi4_country_converter_tests.cpp, src/hoi4_world/localizations/localizations_converter.cpp, src/hoi4_world/localizations/localizations_converter.h, src/hoi4_world/localizations/localizations_converter_tests.cpp, src/hoi4_world/states/hoi4_states_converter.cpp, src/hoi4_world/states/hoi4_states_converter_tests.cpp, src/hoi4_world/world/hoi4_world_converter.cpp, src/hoi4_world/world/hoi4_world_converter_tests.cpp, src/mappers/country/country_mapper.cpp, src/mappers/country/country_mapper.h, src/mappers/country/country_mapper_creator.cpp, src/mappers/country/country_mapper_creator_tests.cpp, src/mappers/country/country_mapper_tests.cpp, src/vic3_world/countries/vic3_countries_importer.cpp, src/vic3_world/countries/vic3_countries_importer_tests.cpp, src/vic3_world/countries/vic3_country.h, src/vic3_world/countries/vic3_country_importer.cpp, src/vic3_world/countries/vic3_country_importer.h, src/vic3_world/countries/vic3_country_importer_tests.cpp, src/vic3_world/world/vic3_world_importer_tests.cpp
Most are rebels. Localization and color are ignored for now so the countries are indistinguishable. But as with everything else, this is a barebones release.
=> Properly handle split countries from save

data/test_files/mappers/MappersCountryCountryMapperCreator/MappingsCanComeFromRulesFile/country_mappings.txt, src/mappers/country/country_mapper_creator.cpp, src/mappers/country/country_mapper_creator.h, src/mappers/country/country_mapper_creator_tests.cpp, src/vic3_to_hoi4_converter.cpp
=> Use country mappings

src/hoi4_world/states/hoi4_states_converter.cpp, src/hoi4_world/states/hoi4_states_converter_tests.cpp
Addresses #280. Vic3 States are sorted by Industry prior to conversion.
=> Sorted states

src/hoi4_world/states/hoi4_states_converter.cpp
=> add resource logging

.github/workflows/windows_build_test_and_push.yml, data/version.txt
=> Roll version

data/configurables/province_mappings.txt
=> russian strays & impassible fudging

src/hoi4_world/countries/hoi4_countries_converter.cpp, src/hoi4_world/countries/hoi4_countries_converter_tests.cpp, src/hoi4_world/countries/hoi4_country_converter_tests.cpp, src/mappers/ideology/ideology_mapper.cpp, src/mappers/ideology/ideology_mapper.h, src/mappers/ideology/ideology_mapper_tests.cpp
=> Ideology mapping algorithm

src/hoi4_world/states/hoi4_state.h, src/hoi4_world/states/hoi4_states_converter.cpp, src/hoi4_world/states/hoi4_states_converter_tests.cpp, src/out_hoi4/states/out_state.cpp, src/out_hoi4/states/out_state_tests.cpp, src/vic3_world/states/vic3_state.h, src/vic3_world/states/vic3_state_importer.cpp, src/vic3_world/states/vic3_state_importer.h, src/vic3_world/states/vic3_state_importer_tests.cpp
Towards #66.
For now just keeping cores and claims simple. Will need to do a more detailed system down the line.
=> Add cores on own land

data/blank_mod/interface/_converter_portraits.gfx, data/configurables/culture_graphics.txt, src/hoi4_world/countries/hoi4_country_converter.cpp, src/hoi4_world/countries/hoi4_country_converter_tests.cpp
HoI4 errors when namelists are too small, merge more often when firstnames < 5.
Misc. portrait name fixes
=> Small namelist

src/hoi4_world/map/possible_path.h, src/hoi4_world/map/possible_path_tests.cpp, src/hoi4_world/map/railways_converter.cpp, src/hoi4_world/map/railways_converter_tests.cpp
=> Merge railways

data/configurables/ideology_mappings.txt, src/hoi4_world/countries/hoi4_countries_converter.cpp, src/mappers/ideology/ideology_mapper.cpp, src/mappers/ideology/ideology_mapper_tests.cpp
=> More Ideology mappings rules

data/test_files/vic3_world/world/test_save.vic3, src/hoi4_world/characters/hoi4_character_converter.cpp, src/hoi4_world/characters/hoi4_character_converter.h, src/hoi4_world/characters/hoi4_character_converter_tests.cpp, src/hoi4_world/characters/hoi4_characters_converter.cpp, src/hoi4_world/characters/hoi4_characters_converter.h, src/hoi4_world/characters/hoi4_characters_converter_tests.cpp, src/hoi4_world/countries/hoi4_countries_converter_tests.cpp, src/hoi4_world/countries/hoi4_country.h, src/hoi4_world/countries/hoi4_country_converter.cpp, src/hoi4_world/world/hoi4_world_converter.cpp, src/hoi4_world/world/hoi4_world_converter_tests.cpp, src/out_hoi4/characters/out_character.cpp, src/out_hoi4/countries/out_country_tests.cpp, src/vic3_world/characters/vic3_character_manager.cpp, src/vic3_world/characters/vic3_character_manager_tests.cpp
Pick field marshals and support limiting # converted
=> Field marshals

Vic3ToHoi4.vcxproj.user, src/hoi4_world/countries/hoi4_countries_converter.cpp, src/hoi4_world/countries/hoi4_countries_converter.h, src/hoi4_world/countries/hoi4_countries_converter_tests.cpp, src/hoi4_world/states/hoi4_states_converter.h, src/hoi4_world/world/hoi4_world_converter.cpp, src/hoi4_world/world/hoi4_world_converter_tests.cpp, src/mappers/world/world_mapper.cpp, src/mappers/world/world_mapper.h, src/mappers/world/world_mapper_builder_tests.cpp, src/vic3_to_hoi4_converter.cpp
Made CountriesConverter use new world_mapping object
=> Cleanup converters 2

Vic3ToHoI4Tests.vcxproj, Vic3ToHoI4lib.vcxproj, Vic3ToHoi4.sln, Vic3ToHoi4.vcxproj, Vic3ToHoi4.vcxproj.user
Add a debug version to the project. Debug version has no optimization, and edit-and-continue support, so its easier to step through.
=> Debug version

src/hoi4_world/countries/hoi4_country.h, src/hoi4_world/countries/hoi4_country_converter.cpp, src/hoi4_world/countries/hoi4_country_converter_tests.cpp, src/out_hoi4/countries/out_country.cpp, src/out_hoi4/countries/out_country_tests.cpp, src/vic3_world/countries/vic3_country.h, src/vic3_world/world/vic3_world_importer.cpp, src/vic3_world/world/vic3_world_importer_tests.cpp
=> Puppet support bug

src/hoi4_world/states/hoi4_states_converter.cpp, src/hoi4_world/states/hoi4_states_converter_tests_state_contents.cpp, src/hoi4_world/world/hoi4_world_converter_tests.cpp, src/vic3_world/states/vic3_state.h, src/vic3_world/world/vic3_world_builder.cpp, src/vic3_world/world/vic3_world_builder.h, src/vic3_world/world/vic3_world_builder_tests.cpp
Better? naval bases conversion. at least, not 1 in each state now.
=> Naval bases

src/hoi4_world/localizations/localizations_converter.cpp, src/hoi4_world/localizations/localizations_converter_tests.cpp, src/hoi4_world/world/hoi4_world_converter_tests.cpp, src/vic3_world/countries/vic3_country.h, src/vic3_world/countries/vic3_country_importer.cpp, src/vic3_world/countries/vic3_country_importer_tests.cpp
=> Better handle split nations 

data/blank_mod/common/ideas/air_spirits.txt, data/blank_mod/common/ideas/army_spirits.txt, data/blank_mod/common/ideas/navy_spirits.txt
Unclear why we have only two army and naval spirits, and no air ones. This just copies in the latest from vanilla.
=> Update officer-corps spirits.

data/blank_mod/common/ideas/air_spirits.txt, data/blank_mod/common/ideas/army_spirits.txt, data/blank_mod/common/ideas/navy_spirits.txt
As recommended by @CaesarVincens.
=> Remove has_foo_academy triggers in spirits.

src/hoi4_world/states/hoi4_states_converter_tests_state_contents.cpp
=> Log resource conversion results

data/configurables/character_traits.txt, data/test_files/configurables/character_traits.txt, src/hoi4_world/characters/hoi4_character_converter.cpp, src/hoi4_world/characters/hoi4_character_converter_tests.cpp, src/hoi4_world/characters/hoi4_characters_converter.cpp, src/hoi4_world/characters/hoi4_characters_converter_tests.cpp, src/hoi4_world/countries/hoi4_country_converter_tests.cpp, src/hoi4_world/countries/hoi4_country_converter_tests_tech.cpp, src/mappers/character/character_trait_mapper.cpp, src/mappers/character/character_trait_mapper.h, src/mappers/character/character_trait_mapper_importer.cpp, src/mappers/character/character_trait_mapper_importer_tests.cpp, src/mappers/character/character_trait_mapper_tests.cpp, src/out_hoi4/characters/out_character.cpp, src/out_hoi4/characters/out_character_tests.cpp
Added mapping for advisor traits so that political advisors aren't generated without game effects.
=> Advisor traits

data/configurables/legacy_ship_types.txt, data/configurables/ship_types.txt, data/configurables/task_force_templates.txt, src/hoi4_world/countries/hoi4_country_converter.cpp
=> Fix navy conversion

src/hoi4_world/states/hoi4_states_converter.cpp
=> Make the minimum naval base level one

src/configuration/configuration_importer.cpp
=> Log remaining unlogged options

src/vic3_world/pacts/pact_importer.cpp
=> add IgnoreUnregisteredItems to pact's target parser

src/vic3_world/wars/war_importer.cpp, src/vic3_world/wars/war_importer.h, src/vic3_world/wars/war_importer_tests.cpp, src/vic3_world/wars/wars_importer_tests.cpp
=> Correctly import attackers and defenders in wars.

data/test_files/mappers/MappersCountryCountryMapperCreator/MappingsCanComeFromRulesFile/country_mappings.txt, src/mappers/country/country_mapper_creator.cpp, src/mappers/country/country_mapper_creator_tests.cpp
=> Disallow tags Windows disallows as filenames.

data/readme.txt, tools/image_modifier.py
Image now fits frame, does not include transparency issues.
=> Improved image_modifier.py

src/configuration/configuration.h, src/configuration/configuration_importer.cpp, src/configuration/configuration_importer.h, src/configuration/configuration_importer_tests.cpp, src/main.cpp, src/vic3_to_hoi4_converter.cpp, src/vic3_to_hoi4_converter.h, src/vic3_world/world/vic3_world_importer.cpp, src/vic3_world/world/vic3_world_importer.h, src/vic3_world/world/vic3_world_importer_tests.cpp
There's really not much brains about this.
=> Plug in installation & savegame version verification from EU4ToVic3.

CMakeLists.txt, data/configurables/culture_graphics.txt, data/test_files/mappers/culture/culture_graphics.txt, src/mappers/culture/culture_graphics_mapper_importer.cpp, src/mappers/culture/culture_graphics_mapper_importer_tests.cpp, src/mappers/culture/culture_graphics_mapping.cpp, src/mappers/culture/culture_graphics_mapping.h, src/out_hoi4/portraits/out_portrait_paths.cpp, src/out_hoi4/portraits/out_portrait_paths_tests.cpp, src/out_hoi4/portraits/out_portraits_tests.cpp
=> Provide scientist portraits
